// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    user_id,
    name,
    type,
    color,
    icon
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, type, color, icon, created_at
`

type CreateCategoryParams struct {
	UserID int64       `json:"user_id"`
	Name   string      `json:"name"`
	Type   string      `json:"type"`
	Color  pgtype.Text `json:"color"`
	Icon   pgtype.Text `json:"icon"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Color,
		arg.Icon,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Color,
		&i.Icon,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = $1 AND user_id = $2
`

type DeleteCategoryParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.UserID)
	return err
}

const getCategories = `-- name: GetCategories :many
SELECT id, user_id, name, type, color, icon, created_at
FROM categories
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetCategories(ctx context.Context, userID int64) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Color,
			&i.Icon,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoriesByUserID = `-- name: GetCategoriesByUserID :many
SELECT id, user_id, name, type, color, icon, created_at
FROM categories
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetCategoriesByUserID(ctx context.Context, userID int64) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategoriesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Color,
			&i.Icon,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
    name = $2,
    type = $3,
    color = $4,
    icon = $5
WHERE id = $1 AND user_id = $6
RETURNING id, user_id, name, type, color, icon, created_at
`

type UpdateCategoryParams struct {
	ID     int64       `json:"id"`
	Name   string      `json:"name"`
	Type   string      `json:"type"`
	Color  pgtype.Text `json:"color"`
	Icon   pgtype.Text `json:"icon"`
	UserID int64       `json:"user_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Color,
		arg.Icon,
		arg.UserID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Color,
		&i.Icon,
		&i.CreatedAt,
	)
	return i, err
}
