// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: migration.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id,
    category_id,
    type,
    amount,
    note,
    transaction_date
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, user_id, category_id, type, amount, note, transaction_date, created_at, updated_at
`

type CreateTransactionParams struct {
	UserID          int64       `json:"user_id"`
	CategoryID      int64       `json:"category_id"`
	Type            string      `json:"type"`
	Amount          float64     `json:"amount"`
	Note            pgtype.Text `json:"note"`
	TransactionDate pgtype.Date `json:"transaction_date"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.CategoryID,
		arg.Type,
		arg.Amount,
		arg.Note,
		arg.TransactionDate,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.Note,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = $1
AND user_id = $2
`

type DeleteTransactionParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UserID)
	return err
}

const getCategoryBreakdown = `-- name: GetCategoryBreakdown :many
SELECT
    c.name,
    SUM(t.amount) AS total
FROM transactions t
JOIN categories c
ON c.id = t.category_id
WHERE
    t.user_id = $1
    AND t.type = 'expense'
GROUP BY c.name
ORDER BY total DESC
`

type GetCategoryBreakdownRow struct {
	Name  string `json:"name"`
	Total int64  `json:"total"`
}

func (q *Queries) GetCategoryBreakdown(ctx context.Context, userID int64) ([]GetCategoryBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getCategoryBreakdown, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCategoryBreakdownRow{}
	for rows.Next() {
		var i GetCategoryBreakdownRow
		if err := rows.Scan(&i.Name, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlySummary = `-- name: GetMonthlySummary :many
SELECT
    DATE_TRUNC('month', transaction_date) AS month,

    COALESCE(
        SUM(CASE WHEN type = 'income' THEN amount END),
        0
    ) AS income,

    COALESCE(
        SUM(CASE WHEN type = 'expense' THEN amount END),
        0
    ) AS expense

FROM transactions
WHERE user_id = $1
GROUP BY month
ORDER BY month DESC
`

type GetMonthlySummaryRow struct {
	Month   pgtype.Interval `json:"month"`
	Income  interface{}     `json:"income"`
	Expense interface{}     `json:"expense"`
}

func (q *Queries) GetMonthlySummary(ctx context.Context, userID int64) ([]GetMonthlySummaryRow, error) {
	rows, err := q.db.Query(ctx, getMonthlySummary, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlySummaryRow{}
	for rows.Next() {
		var i GetMonthlySummaryRow
		if err := rows.Scan(&i.Month, &i.Income, &i.Expense); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSummary = `-- name: GetSummary :one
SELECT
    COALESCE(
        SUM(CASE WHEN type = 'income' THEN amount END),
        0
    ) AS total_income,

    COALESCE(
        SUM(CASE WHEN type = 'expense' THEN amount END),
        0
    ) AS total_expense

FROM transactions
WHERE user_id = $1
`

type GetSummaryRow struct {
	TotalIncome  interface{} `json:"total_income"`
	TotalExpense interface{} `json:"total_expense"`
}

func (q *Queries) GetSummary(ctx context.Context, userID int64) (GetSummaryRow, error) {
	row := q.db.QueryRow(ctx, getSummary, userID)
	var i GetSummaryRow
	err := row.Scan(&i.TotalIncome, &i.TotalExpense)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, user_id, category_id, type, amount, note, transaction_date, created_at, updated_at
FROM transactions
WHERE id = $1
AND user_id = $2
`

type GetTransactionByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.Note,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT
    t.id,
    t.user_id,
    t.category_id,
    c.name AS category_name,
    t.type,
    t.amount,
    t.note,
    t.transaction_date,
    t.created_at
FROM transactions t
JOIN categories c
ON c.id = t.category_id
WHERE t.user_id = $1
ORDER BY t.transaction_date DESC
`

type ListTransactionsRow struct {
	ID              int64       `json:"id"`
	UserID          int64       `json:"user_id"`
	CategoryID      int64       `json:"category_id"`
	CategoryName    string      `json:"category_name"`
	Type            string      `json:"type"`
	Amount          float64     `json:"amount"`
	Note            pgtype.Text `json:"note"`
	TransactionDate pgtype.Date `json:"transaction_date"`
	CreatedAt       time.Time   `json:"created_at"`
}

func (q *Queries) ListTransactions(ctx context.Context, userID int64) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsRow{}
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.CategoryName,
			&i.Type,
			&i.Amount,
			&i.Note,
			&i.TransactionDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET
    category_id = $3,
    type = $4,
    amount = $5,
    note = $6,
    transaction_date = $7,
    updated_at = NOW()
WHERE id = $1
AND user_id = $2
RETURNING id, user_id, category_id, type, amount, note, transaction_date, created_at, updated_at
`

type UpdateTransactionParams struct {
	ID              int64       `json:"id"`
	UserID          int64       `json:"user_id"`
	CategoryID      int64       `json:"category_id"`
	Type            string      `json:"type"`
	Amount          float64     `json:"amount"`
	Note            pgtype.Text `json:"note"`
	TransactionDate pgtype.Date `json:"transaction_date"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.UserID,
		arg.CategoryID,
		arg.Type,
		arg.Amount,
		arg.Note,
		arg.TransactionDate,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.Note,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
