// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        int64       `json:"id"`
	UserID    int64       `json:"user_id"`
	Name      string      `json:"name"`
	Type      string      `json:"type"`
	Color     pgtype.Text `json:"color"`
	Icon      pgtype.Text `json:"icon"`
	CreatedAt time.Time   `json:"created_at"`
}

type Transaction struct {
	ID              int64       `json:"id"`
	UserID          int64       `json:"user_id"`
	CategoryID      int64       `json:"category_id"`
	Type            string      `json:"type"`
	Amount          float64     `json:"amount"`
	Note            pgtype.Text `json:"note"`
	TransactionDate pgtype.Date `json:"transaction_date"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

type User struct {
	ID           int64     `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}
